defaults:  
  - _self_  
  - data
  - query
  - statistics
  # - override hydra/hydra_logging: disabled  
  # - override hydra/job_logging: disabled 
  
hydra:  
  output_subdir: null 
  run:  
    dir: .